### ISSUE TITLE
registers

### ISSUE THREAD

**Issue by jonghwan7028** [richard-clark/PyDynamixel#1]
Problem below

from pydynamixel import dynamixel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jongkim/anaconda/lib/python3.6/site-packages/pydynamixel/dynamixel.py", line 121, in <module>
    import registers
ModuleNotFoundError: No module named 'registers'

I am currently using anaconda jupyter notebook (5.4.0)64-bit and when I run code above, keep showing 'registers' problem. How can I fix it. Thanks.

**Comment by quentinsf** [comment]
Probably too late to be useful, but...

This is a Python 3 problem.  If you can run under Python 2, you won't have this issue.

Alternatively, I've just made a fork [here](https://github.com/quentinsf/PyDynamixel) which should work under Python 3 (but probably won't work under Python 2).
